[package]
name = "monster-ugi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monster_chess = "0.0.5"
rand = "0.8.5"
